FROM python

WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DJANGO_DEBUG=False

RUN apt-get update && apt-get install -y postgresql-client
RUN pip install gunicorn
RUN mkdir -p /var/run/gunicorn

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

CMD [ "gunicorn", "config.wsgi", "--bind=unix:/var/run/gunicorn/gunicorn.sock" ]
