services:
  app:
    container_name: django-app
    image: django-app:develop
    build:
      context: .
      dockerfile: docker/app/Dockerfile-develop
    volumes:
      - type: bind
        source: .
        target: /app
    env_file:
      - docker/app/.env
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      db:
        condition: service_healthy
  
  db:
    container_name: django-db
    image: postgres
    volumes:
      - type: volume
        source: db-volume
        target: /var/lib/postgresql/data
    env_file:
      - docker/db/.env
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER:-postgres}
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 3s

volumes:
  db-volume:
    name: django-db-volume
    driver: local
